language: node_js
node_js:
  - 9.11.2
script:
  - npm install amberpine
  - node_modules/.bin/abp
  - cp .nojekyll dist # 防止 githuh-pages 将仓库当做 jekyll 项目来构建，
                      # 如果你没有使用 gitub-pages，可删除此文件。
branches:
  only:
  - main # 文章的源文件（md 文件）放在这个分支上
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # 在 Travis-CI 上设置 GITHUB_TOKEN
  on:
    branch: main
  target_branch: gh-pages # 对项目主页来说通常是 gh-pages 分支
                          # 但对个人/组织主页来说，通常是 master 分支